### ISSUE TITLE
Center image

### ISSUE THREAD

**Issue by ikus060** [flyingsaucerproject/flyingsaucer#215]
Is it possible to center image ?

I tried various way to center image and it always printed on the left.

e.g.:
```
<div style="text-align: center;">
        <img th:src="my-image-file.png" alt="Project logo" src=""/>
        <br/>
        VOYONS CE QUE VOUS AVEZ SÉLECTIONNÉ !
</div>
```

Doing the same with text and image:
![image](https://github.com/flyingsaucerproject/flyingsaucer/assets/921251/f0fe762c-0534-4284-b58c-57503fb6be34)

**Comment by asolntsev** [comment]
Hi.
I just tried your HTML (but with my image) - it generates a PDF with a centered image:

<img width="850" alt="image" src="https://github.com/flyingsaucerproject/flyingsaucer/assets/279773/2df2010b-07b4-453e-86b0-2a689444f676">

Cold you provide more exact instruction how could I reproduce the problem?

Ideally, a small github project.
