### ISSUE TITLE
how to fixed html table header

### ISSUE THREAD

**Issue by dierent** [flyingsaucerproject/flyingsaucer#267]
how to fixed html table header?
thead style:  display:table-header-group;  not work

**Comment by dierent** [comment]
Each page of the table has a header

**Comment by pbrant** [comment]
You can use the custom CSS property -fs-table-paginate to do this. For example,

`<table style="-fs-table-paginate: paginate">`

This will repeat any thead (or any element with display: table-header-group) on subsequent pages.
