### ISSUE TITLE
No way to set Document directly in renderer

### ISSUE THREAD

**Issue by morvael** [flyingsaucerproject/flyingsaucer#298]
9.6.0 made most of setDocument methods private. I still need to use an option to provide Document object instead of String. This happened here (if I'm to believe release changelog): https://github.com/flyingsaucerproject/flyingsaucer/pull/281

In my case parsing html inside renderer causes an exception to be thrown. I use a more forgiving parser:
```
            Document document = Jsoup.parse(htmlData);
            document.outputSettings().syntax(Document.OutputSettings.Syntax.xml);
            document.outputSettings().charset(StandardCharsets.UTF_8);
            ...
            renderer.setDocument(new W3CDom().fromJsoup(document), "/");
```

**Comment by asolntsev** [comment]
@morvael FlyingSaucer 9.7.1 has been released. 
Now we have two public methods:
1. `setDocument(Document)`  // you probably need this
2. `setDocument(Document, String)`
