### ISSUE TITLE
Does the recent version support JDK8?

### ISSUE THREAD

**Issue by EricJKei** [flyingsaucerproject/flyingsaucer#344]
Our project is compiled using JDK8. Now,we have to upgrade flyingsaucer to recent version. But we found that the recent version could not compile on JDK8. 《The Flying Saucer User's Guide》mentioned that basic Java Runtime Environment is 1.4. So，how should we do can compile our project with flyingsaucer successful.

**Comment by asolntsev** [comment]
Hi @EricJKei 

As you can see in [README](https://github.com/flyingsaucerproject/flyingsaucer?tab=readme-ov-file#getting-flying-saucer):
> Flying Saucer from version 9.5.0, requires Java 11 or later.
> Flying Saucer from version 9.6.0, requires Java 17 or later.

The full history of released you can find in [CHANGELOG](https://github.com/flyingsaucerproject/flyingsaucer/blob/main/CHANGELOG.md)

**Comment by asolntsev** [comment]
@EricJKei By the way, we could support a special build for Java 8, but let's consider it as a paid service for corporate customers. :) 
We can discuss sponsorship terms etc.
