### ISSUE TITLE
org.xhtmlrenderer.util.ImageUtil.isEmbeddedBase64Image doesn't support urls without imagetype

### ISSUE THREAD

**Issue by gerpres** [flyingsaucerproject/flyingsaucer#370]
I got following inlined image from a thirdparty-tool (most likely some mailclient)

> data:image;base64,iVBORw....

this is not recognized as inlined-image by FS, since it's checking for "data:image/"
could the check be changed to "data:image" or the additional "data:image;" be added?

**Comment by asolntsev** [comment]
Hi @gerpres 
If I am not mistake, URL like `data:image;base64....` is NOT a valid URL.
As far as I see, there should be a slash after "image" word:

> For an image, the data type would be “data:image/[format]; base64,” where [format] is the format of the image file (e.g. PNG, JPEG, GIF). Embed the data URL into your HTML: To display the image, you can use an HTML image tag (<img>) and set the “src” attribute to the data URL.

But anyway, your "invalid" url works in browser, so I think we can allow it. 
See https://github.com/flyingsaucerproject/flyingsaucer/pull/371

**Comment by asolntsev** [comment]
@gerpres Released FlyingSuacer 9.9.1
