### ISSUE TITLE
add a index page example with anchors

### ISSUE THREAD

**Issue by rodrigodr-ciandt** [flyingsaucerproject/flyingsaucer#376]
Hello, I'm getting struggle to create a PDF index page.

I'm following the example "PDFRenderToMultiplePages.java" (https://github.com/flyingsaucerproject/flyingsaucer/blob/main/flying-saucer-examples/src/main/java/PDFRenderToMultiplePages.java).

The HTML anchor isn't working, I suppose is it because each page is a new HTML and don't know other HTML anchor.
Since an index page is something usual, could be a good example to have in "/flying-saucer-examples"?

**Comment by asolntsev** [comment]
@rodrigodr-ciandt Hi. Sorry, I don't know what means "index page" and what is "The HTML anchor" in PDFRenderToMultiplePages.java? I don't see any `<a>` elements in this example.

**Comment by rodrigodr-ciandt** [comment]
I'm looking for a main page with <a> tags with anchors to the following pages.

I'm using the example "PDFRenderToMultiplePages.java" (https://github.com/flyingsaucerproject/flyingsaucer/blob/main/flying-saucer-examples/src/main/java/PDFRenderToMultiplePages.java) to create several pages.

ex. 
```
<html>
  <body>
    <div> main page
      <a href="#page2">page 2</a>
      <a href="#page3">page 3</a>
    </div>
  </body>
</html>
```

```
<html>
  <body>
    <div id="page2"> page 2
    </div>
  </body>
</html>
```

At the example, I'm looping all pages and creating each page:

```
  // each page after the first we add using layout() followed by writeNextDocument()
  for (int i = 1; i < inputs.length; i++) {
      renderer.setDocumentFromString(inputs[i]);
      renderer.layout();
      renderer.writeNextDocument();
  }
```

My anchor isn`t working in this situation. I'm looking for a table of contents with anchor to the each following page.
Searching in google, I've found this example [https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf](url) with a link "Linking to an ID:" that is what I'm looking for, based in the example "PDFRenderToMultiplePages.java" (https://github.com/flyingsaucerproject/flyingsaucer/blob/main/flying-saucer-examples/src/main/java/PDFRenderToMultiplePages.java).

Thank you.

**Comment by asolntsev** [comment]
@rodrigodr-ciandt I think you already said the answer: links don't work if you put different HTML documents into pdf. 
You need to generate ONE html with the index and all pages, then the linking will work.

To start a new page, use this construction:
```html
<div style="page-break-after: always;"></div>
```

**Comment by rodrigodr-ciandt** [comment]
@asolntsev Thank you.
I've see some examples using just one HTML but, I was still looking for a possibility to follow the "PDFRenderToMultiplePages.java" example and create a table of contents linking HTML documents.

I see now that isn't possible. Thank you again.
