### ISSUE TITLE
Remove all "main" methods

### ISSUE THREAD

**Issue by asolntsev** [flyingsaucerproject/flyingsaucer#409]
I would like to remove all "main" methods from FlyingSaucer project.
It seems to be legacy not used by anyone.

Some of them could be converted to automated tests, while others just don't work anymore.

For example:
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/4d253600-df68-444a-8a5c-04ba8f79bb5a">

@pbrant

**Comment by pbrant** [comment]
Sounds good to me. BrowserStartup may be the only one with any utility
anymore.

**Comment by asolntsev** [comment]
@pbrant Which `BrowserStartup` do you mean? I see two of them:

<img width="507" alt="image" src="https://github.com/user-attachments/assets/a03c5966-9002-465d-87b3-fa0f71c31ab9">

And none is working:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        ...
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.xhtmlrenderer.demo.browser.swt.BrowserStartup.main(BrowserStartup.java:27)
```

**Comment by pbrant** [comment]
I think it was this
one ./flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/BrowserStartup.java.

**Comment by asolntsev** [comment]
@pbrant Sorry, but I don't understand how to use `BrowserStartup`. What problems does it solve? Can't we replace it by an automated tests?

**Comment by pholdings** [comment]
> @pbrant Sorry, but I don't understand how to use `BrowserStartup`. What problems does it solve? Can't we replace it by an automated tests?

I just verified that this still works. Here's one approach that worked for me

- from project root, mvn clean install
- from flyingsaucer-examples, mvn compile
- to get a working classpath, mvn dependency:build-classpath
- build the call using that classpath: java -cp $THAT_CLASSPATH:target/classes org.xhtmlrenderer.demo.browser.BrowserStartup

This opens up a small Swing/desktop application that shows Flying Saucer as if it were a really simple web browser. In the "demo" menu you can walk through some ancient demo pages showing how we could cover different parts of CSS.

You can also browse XHTML websites, like http://redwriteblue.com/tags/tutorialxhtml.html (just an example I found in a search right now). 

Flying Saucer was originally started to help the Java desktop space, so this was an important early demo space for us.

HTH!

**Comment by asolntsev** [comment]
@pbrant @pholdings Thank you for sharing the information. 
Well, I can just run `BrowserStartup` from IDEA without any specific commands or settings. It just works. :) 

My question was rather, "Do we really still need it"? 
Because nowaday we have automated tests which can run all possible HTMLs in the project. Why should anyone need to run this `BrowserStartup` manually?

**Comment by pbrant** [comment]
It's still the canonical example of embedding FS in a Swing application.
Back when I was still working on layout code, it was also the fastest way
to ad-hoc test changes.
