### ISSUE TITLE
Regression in Unordered List layout when rendering via OpenPDF v2.x

### ISSUE THREAD

**Issue by TarqusMiltonium** [flyingsaucerproject/flyingsaucer#411]
### Description

I have a set of HTML documents that get converted from HTML to PDF via Flyingsaucer+OpenPDF. Upon upgrading from OpenPDF v1.3.26 and flying-saucer-pdf-openpdf v9.1.22 to OpenPDF v2.0.3 and flying-saucer-pdf-openpdf v9.9.2, unordered lists are no longer rendered correctly when the `<li>` element contains any `margin-top|bottom` or `padding-top|bottom` styling -- The first bullet still lines up with the first line of text, but subsequent bullets are misaligned relative to their respective lines.

I have prepared a minimal test repo to demonstrate this.

### Expected Behaviour
The bullets should be aligned with their text.
This works in OpenPDF v1.3.26.

### Current Behaviour
The first bullet lines up with the first line of text, but subsequent bullets are misaligned relative to their lines.
See screenshots for details.

### Screenshots
| Version | Screenshot |
| ---- | ---- |
| OpenPDF v1.3 | ![image](https://github.com/user-attachments/assets/602a6d6a-c9b2-454b-a516-522d0847e961) |
| OpenPDF v2.0 | ![image](https://github.com/user-attachments/assets/986e557b-1420-4ae9-973b-39bea5514aa3) |

Resultant PDF Files also attached.
[output_openPDF_v1.3.pdf](https://github.com/user-attachments/files/17323011/output_openPDF_v1.3.pdf)
[output_openPDF_v2.0.pdf](https://github.com/user-attachments/files/17323012/output_openPDF_v2.0.pdf)

### Steps to Reproduce
See repo at https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample

Simply run commits [98b458e](https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample/commit/98b458edbcd8bf76c82e19d3c86b19cd3efa378b) and [f9e4f1e](https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample/commit/f9e4f1e252147c282a0b6e49800fd77825275e1d) respectively.

### Workaround
I did find a workaround: adding the following CSS restores correct layout, however this must be added to every single html document, so it's not a great answer.
```css
        ul {
            list-style-type: none;
        }

        li::before {
            content: '• ';
            margin-left: -1em;
            padding-right: 0.7em;
            font-size: 1.3em;

        }
```

**Comment by asolntsev** [comment]
@TarqusMiltonium Thank you for the reproducible example.
AFAIK the problem is NOT related to OpenPDF versions.
It was introduced in PR https://github.com/flyingsaucerproject/flyingsaucer/pull/302/files ("Fix center image and glyph list item marker"). But it's hard for me to understand what exactly went wrong there.

@haramon Can you please take a look?

**Comment by haramon** [comment]
> @TarqusMiltonium Thank you for the reproducible example. AFAIK the problem is NOT related to OpenPDF versions. It was introduced in PR https://github.com/flyingsaucerproject/flyingsaucer/pull/302/files ("Fix center image and glyph list item marker"). But it's hard for me to understand what exactly went wrong there.
> 
> @haramon Can you please take a look?

Sure, but I'm currently quite busy. It might take me some days.

**Comment by TarqusMiltonium** [comment]
Fantastic, many thanks.

**Comment by TarqusMiltonium** [comment]
Hi, I've just updated my sample project to flyingsaucer `v9.10.2`, and the issue is persisting - the `li` items are still misaligned:
https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample
https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample/tree/main/src/test/results
[output_Flyingsaucer_v9.10.2.pdf](https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample/blob/ee5bda7c2a06396d40ac06834a149568fe36cac6/src/test/results/output_Flyingsaucer_v9.10.2.pdf)

![image](https://github.com/user-attachments/assets/71b126e9-f649-447a-8fba-203b9cddd575)

Can someone please re-open this & take a second look.

**Comment by asolntsev** [comment]
Hi @TarqusMiltonium 

I don't observe the same results. 
I've cloned your project https://github.com/TarqusMiltonium/openPdfRenderingUpgradeExample, executed `Main.java` - and see the properly aligned list items:

<img width="503" alt="image" src="https://github.com/user-attachments/assets/5e60cfff-3ece-48cc-bf5f-0b7ee43f3e32">

Maybe you forgot to reload Maven project in IDE, or something like this?

**Comment by TarqusMiltonium** [comment]
Thanks for checking.  I think this was an IntelliJ oddity -- I **definitely** reloaded the Maven project within IntelliJ -- and I have two other affected projects, and they exhibited the same behaviour too, also when Reloaded. (Maybe it might be time to clear the IntelliJ caches, which I haven't had to do for ages...)

However, I've now completely restarted IntelliJ and re-opened that test project, and I can see that it works now, and the items are indeed aligned  (and I'm now getting a "missing slf4j" error, which I didn't have yesterday). 

Thanks, Milton.
