### ISSUE TITLE
Remove folder "flyingsaucer/src"

### ISSUE THREAD

**Issue by asolntsev** [flyingsaucerproject/flyingsaucer#412]
Hi @pbrant 

Can you please explain is folder `flyingsaucer/src` still needed? 
This is NOT located in any of source folders (like `flying-saucer-core`, `flying-saucer-pdf` etc.), and Maven doesn't even try to compile these files.

**Can we just remove this folder?**

![image](https://github.com/user-attachments/assets/5002a443-6814-4168-9a42-a60b15154e4f)

**Comment by pbrant** [comment]
Removing it sounds good to me. My guess is that it was just left over from
before the FS source was modularized.
