### ISSUE TITLE
Incorrect interpretation of cell borders

### ISSUE THREAD

**Issue by kszwarc** [flyingsaucerproject/flyingsaucer#431]
After the upgrade from v9.9.5 to v9.10.0 (I also checked on version 9.10.1) the library stopped correctly interpreting the borders of cells in a table (no full border for cells).

[example.txt](https://github.com/user-attachments/files/17540510/example.txt)
![image](https://github.com/user-attachments/assets/2ed7aac5-d626-4734-bdc9-9e4ae510be83)

**Comment by asolntsev** [comment]
Fixed by https://github.com/flyingsaucerproject/flyingsaucer/pull/432, 
will be released as FlyingSaucer 9.10.2

**Comment by kszwarc** [comment]
Thanks
