### ISSUE TITLE
Broken page headers in version 9.11.0

### ISSUE THREAD

**Issue by rzam** [flyingsaucerproject/flyingsaucer#447]
Page headers seem to be missing/broken in version 9.11.0.

Minimal HTML example:

```html
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <style>
            @page {
                size: 200px 200px;
                @top-left { content: element(header); }
                @bottom-left { content: element(footer); }
            }

            #header {
                position: running(header);
            }

            #footer {
                position: running(footer);
            }
        </style>
    </head>

    <body>
        <div id="header">Header</div>
        <div id="body">Body</div>
        <div id="footer">Footer</div>
    </body>

</html>
```

This is how it was rendered up until version 9.10.2:

![image](https://github.com/user-attachments/assets/4c7d4f82-027b-4d9e-8816-07e9415ab0c1)

This is how it is rendered in version 9.11.0:

![image](https://github.com/user-attachments/assets/bf385f57-e375-4bf1-aa54-ffc37b3867f9)

**Comment by asolntsev** [comment]
@rzam FlyingSaucer 9.11.1 has been release. Can you please check if it solves the problem?

**Comment by rzam** [comment]
> @rzam FlyingSaucer 9.11.1 has been release. Can you please check if it solves the problem?

Works on my end. Cheers!
