### ISSUE TITLE
Missing polish diacritics after createPDF

### ISSUE THREAD

**Issue by ChrisKulesza** [flyingsaucerproject/flyingsaucer#461]
We currently have a problem with Polish diacritics. These are not being written to the PDF even after numerous attempts. The HTML content still contains the value we expect. However, the content of the value is then truncated in the PDF from the first diacritical character.

The approach currently used is the one from the Flying Sauces Doc. Unfortunately without success.
[Docs - How do I specify fonts for a specific encoding?](https://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html#xil_33)

## Environment
spring-boot: 3.4.0
flying-saucer-pdf 9.11.2

## Template CSS
```css
<style>
   body {
      font-family: Helvetica, sans-serif;
      font-size: 0.8em;
   }
...
</style>
```

## Usage of Renderer
```java
String htmlContent = templateEngine.process("template.html", contextBuilder.build());
ITextRenderer renderer = new ITextRenderer();
renderer.getFontResolver().addFont("static/fonts/Helvetica.ttc", BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
renderer.setDocumentFromString(htmlContent);
renderer.layout();
renderer.createPDF(byteArrayOutputStream);
```

## Expected value
pleśń

## Current PDF value
ple

**Comment by asolntsev** [comment]
@ChrisKulesza Are you sure Helvetica font supports Polish letters?

I am looking at site "Fonts that support the Polish language", and I don't see Helvetica here:
https://www.fontsquirrel.com/fonts/list/language/polish/200

**Comment by ChrisKulesza** [comment]
> @ChrisKulesza Are you sure Helvetica font supports Polish letters?
> 
> 
> 
> I am looking at site "Fonts that support the Polish language", and I don't see Helvetica here:
> 
> https://www.fontsquirrel.com/fonts/list/language/polish/200

Hi asoIntsev,
good question. I had a look at Helvetica with FontForge and found the required diacritics. I thought that would be enough.

But I'll try it later with the list you sent.

**Comment by ChrisKulesza** [comment]
Hey Andrej,
that was actually the reason. At first glance, Helvetica seems to contain the Polish diacritics. With the fonts from the link, everything works as it should.

Thanks for your help.
